### ISSUE TITLE
Ultimate unicorn mod compatibility

### ISSUE THREAD

**Issue by AdaraChristine** [NightKosh/Gravestone-mod-Extended#124] opened 2018-02-24 07:28 UTC
Minecraft version 1.12.2
Forge-14.23.2.2611
GraveStone-1.12.2-Extended-1.3.0b4

Ticking entity

java.lang.ClassCastException: com.hackshop.ultimate_unicorn.mobs.EntityUnicorn cannot be cast to net.minecraft.entity.passive.EntityHorse
	at nightkosh.gravestone_extended.item.corpse.HorseCorpseHelper.setNbt(HorseCorpseHelper.java:90)
	at nightkosh.gravestone_extended.item.corpse.CorpseHelper.getCorpse(CorpseHelper.java:150)
	at nightkosh.gravestone_extended.helper.GraveGenerationHelper.lambda$addMobsItemsHandlers$14(GraveGenerationHelper.java:54)
	at nightkosh.gravestone_extended.helper.GraveGenerationHelper$$Lambda$1880/62901118.addItems(Unknown Source)
	at nightkosh.gravestone.helper.GraveGenerationHelper.createHorseGrave(GraveGenerationHelper.java:240)
	at nightkosh.gravestone.core.event.EventsHandler.onEntityLivingDeath(EventsHandler.java:83)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1591_EventsHandler_onEntityLivingDeath_LivingDeathEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:585)
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1159)
	at net.minecraft.entity.passive.AbstractHorse.func_70645_a(AbstractHorse.java:612)
	at net.minecraft.entity.passive.AbstractChestHorse.func_70645_a(SourceFile:80)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:66)
	at net.minecraft.entity.passive.AbstractHorse.func_70097_a(AbstractHorse.java:236)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:232)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2087)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.passive.AbstractHorse.func_70071_h_(AbstractHorse.java:682)
	at com.hackshop.ultimate_unicorn.mobs.EntityMagicalHorse.func_70071_h_(EntityMagicalHorse.java:1002)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

https://pastebin.com/FGLvxLcw

**Comment by NightKosh** [comment] 2018-03-04 21:31
Hello. Unfortunately I can't reproduce your problem. Any way I fixed the part of my code which was mentioned in your crash log, so it should help. 
Also I added 3 new configuration options:
* CreateCorpsesForModdedNotVanillaDogs
* CreateCorpsesForModdedNotVanillaCats
* CreateCorpsesForModdedNotVanillaHorses

Please give me to know if you'll need additional fixes.

P.S. I'll provide link on a new version here when it will be released.

**Closed as completed by NightKosh** 2018-03-04 21:31 UTC
Labels: compatibility, crash

**Comment by AdaraChristine** [comment] 2018-03-04 23:19
THANKS!!
